### ISSUE TITLE
Start 화면 UI

### ISSUE THREAD

**Issue by cje172** [CareSheep/CareSheep_Android#2]
## 내용
- splash 화면 UI
- 시작하기 화면 UI
- 내 정보 입력 화면 UI

## ToDo
- [x] SplashScreen compat 라이브러리 사용
- [x] 구글 로그인 버튼
- [x] Custom EditText, Button
