### ISSUE TITLE
마이페이지 구현

### ISSUE THREAD

**Issue by cje172** [CareSheep/CareSheep_Android#31]
## 내용
- 마이페이지 구현
- 어르신 루틴 정보 화면
- 어르신 연결하기 화면

## ToDo
- [x] 마이페이지 사용자 정보 표시
- [x] 어르신 루틴 정보 UI
- [x] 어르신 연결하기  UI
- [x] Firebase - 어르신 연결 기능 구현
