### ISSUE TITLE
어르신 위치 추적 시, 포그라운드화 구현

### ISSUE THREAD

**Issue by cje172** [CareSheep/CareSheep_Android#81]
## 내용
- 보호자에게 어르신의 위치를 실시간으로 제공하기 위해 어르신이 지도 화면에 진입할 시, 실시간 위치 추적 서비스를 시작한다. 이때, 실시간 위치 정보를 전달하기 위해 위치 업데이트 제한이 있는 백그라운드 대신 포그라운드로 구현한다.
- 참고 사이트: [Android 개발자 - 백그라운드 위치 제한](https://developer.android.com/about/versions/oreo/background-location-limits?hl=ko), [Android 개발자 - 포그라운드 서비스](https://developer.android.com/guide/components/foreground-services)

## ToDo
- [ ] 어르신이 지도 화면 진입 시 위치 권한 허용되어 있으면 포그라운드화 (상태 표시줄 알림 표시)
- [ ] 어르신의 실시간 위치 정보를 DB에 저장 및 보호자 지도 화면에서 조회
- [ ] 위치 권한이 거부되거나 사용자가 포그라운드 서비스 종료 버튼 누르면 포그라운드 종료
